### ISSUE TITLE
New clone of repo can't run manage.py migrate (haystack conflict)?

### ISSUE THREAD

**Issue by jeanconn** [x-calibre/astropython#9]
I get this haystack conflict trying to run the setup from scratch:

```
(astro)user@surfman ~/git/astropython/astropython $ python manage.py migrate
/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):

/opt/anaconda/envs/astro/lib/python2.7/site-packages/secretballot/__init__.py:8: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/opt/anaconda/envs/astro/lib/python2.7/site-packages/haystack/utils/__init__.py:12: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/opt/anaconda/envs/astro/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/haystack/__init__.py", line 73, in <module>
    import abouchet 
  File "/opt/anaconda/envs/astro/lib/python2.7/site-packages/haystack/abouchet.py", line 21, in <module>
    from haystack.utils import xrange
ImportError: cannot import name xrange
```

**Comment by jeanconn** [comment]
I pip uninstalled django-haystack and haystack, and then reinstalled just django-haystack.  python manage.py migrate then completed without errors.

**Comment by x-calibre** [comment]
Need to update the requirements.txt !

**Comment by x-calibre** [comment]
Updated requirements.txt and removed Haystack completely (replacing it with Watson) 
Thanks for pointing it out !
